repos:
  # Pre-commit hooks for Python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: requirements-txt-fixer

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Ruff linter (replaces flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # Local hooks (custom make commands)
  - repo: local
    hooks:
      - id: build-script
        name: Build single script
        entry: make build
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: run-tests
        name: Run tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
