requires 'AnyEvent';
requires 'Config::Neat', 'v1.302.0';
requires 'Hash::Diff';
requires 'Linux::Inotify2';
requires 'List::MoreUtils';
requires 'Log::Any';
requires 'Log::Any::Adapter';
requires 'Log::Any::Adapter::Log4perl';
requires 'Log::Log4perl';
requires 'YAML::Syck';
requires 'feature';
