name: Compatibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run monthly on the 1st day at 08:00 UTC
    - cron: '0 8 1 * *'

jobs:
  test-min-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]  # Test with minimum supported Python version
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install minimum versions
      run: |
        python -m pip install --upgrade pip
        # Install minimum versions of dependencies
        pip install pytest==7.0.0 black==22.0.0 ruff==0.1.0 isort==5.0.0
    
    - name: Run tests with minimal dependencies
      run: |
        python -m pytest tests/ -v
    
    - name: Test script build with minimal deps
      run: |
        python build_single_script.py
        chmod +x enr.sh
        ./enr.sh --help

  test-latest-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]  # Test with latest Python version
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install latest versions
      run: |
        python -m pip install --upgrade pip
        # Install latest versions of all dependencies
        pip install --upgrade pytest black ruff isort safety bandit
    
    - name: Run tests with latest dependencies
      run: |
        python -m pytest tests/ -v
    
    - name: Full lint check with latest tools
      run: |
        ruff check .
        black --check .
        isort --check-only .
    
    - name: Security check with latest tools
      run: |
        safety check || true  # Don't fail on security issues, just report
        bandit -r enr/ || true
