name: Dependencies

on:
  schedule:
    # Runs at 09:00 UTC every Monday
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Update pre-commit hooks
      run: |
        pip install pre-commit
        pre-commit autoupdate
    
    - name: Check for dependency vulnerabilities
      run: |
        pip install safety
        safety check --json --output safety-report.json || true
        if [ -f safety-report.json ]; then
          echo "Security vulnerabilities found:"
          cat safety-report.json
        fi
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies and pre-commit hooks"
        title: "Update dependencies and pre-commit hooks"
        body: |
          Automated dependency update:
          
          - Updated pre-commit hooks to latest versions
          - Checked for security vulnerabilities
          
          Please review the changes before merging.
        branch: update-dependencies
        delete-branch: true
